### ISSUE TITLE
Comments API

### ISSUE THREAD

**Issue by AlexLMeow** [helloworld1812/SaferCityBackend#12]
Current use cases only require retrieving list of comments associated with a single report. Optional to support batch operations etc.

```
body: String (MAX 255)
timestamp: timestamp
author: String (user id)
author_name: String (name to show users)
avatar: Image
```

**Comment by AlexLMeow** [comment]
though user system is not yet implemented

**Comment by AlexLMeow** [comment]
`avatar` and `author_name` will be pulled from user table and served with each `comment` object. This prevents multiple endpoint calls from mobile client to retrieve user avatar and name.

**Comment by AlexLMeow** [comment]
Yes please change some of the field names to `author_<field>`, for id, avatar, name.

**Comment by by-code** [comment]
Currently only "time" and "text" fields are supported. User information will be added later when users entity is implemented
