### ISSUE TITLE
Support pagination for "/comment?reportId={reportId}"

### ISSUE THREAD

**Issue by by-code** [helloworld1812/SaferCityBackend#20]
Should support following fields:
```
before: timestamp
```

Returns list of comments for specified report which time is before specified `before`.

**Comment by AlexLMeow** [comment]
Do you think `/report/:id/comment` would be better? That seems to be the convention

**Comment by by-code** [comment]
The url looks good to me. However I'm not sure about code location - if it's `/report/:id/comment` then it should be in "reports" router and that means that this router should have dependency on "comments". 
Since right now we have only mobile client lets go with `/comment?reportId={reportId}` since this url is not visible anywhere. If it were webpage it would definitely should be `/reports/{reportId}/comments`

**Comment by AlexLMeow** [comment]
OK that sounds good
