### ISSUE TITLE
User account CRUD

### ISSUE THREAD

**Issue by AlexLMeow** [helloworld1812/SaferCityBackend#31]
Provide API to create and delete accounts.

Frontend will use account kit and facebook login libraries to perform login; but account creation and deletion will have to inform backend too.

User accounts have an associated 'name' string. Frontend should pass backend the desired name on account creation/update regardless of login type (fb or phone). For fb login frontend will check the name and pass it to you, so you don't have to call facebook for name.

Backend should store names so paginated results from other API calls can include the author names to minimize number of queries to backend or facebook servers.

What do you think? Anything to clarify?

**Comment by by-code** [comment]
Fixed by 5f56576

**Comment by by-code** [comment]
I think there should be no "delete" method for user unless it is absolutely necessary
